name: Implementer (Claude)
permissions:
  contents: write
  pull-requests: write
on:
  issues:
    types: [opened, edited, labeled]
jobs:
  build-feature:
    if: contains(github.event.issue.labels.*.name, 'spec')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Spec
        id: spec
        run: |
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          echo "${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Ask Claude to implement
        id: claude
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python - << 'PY'
import os, json, requests
spec = """${{ steps.spec.outputs.BODY }}"""
prompt = f"""
You are Claude Code. Implement the SPEC CARD by returning a set of files with this exact format:

<<<file:relative/path>>>
...code...
<<<endfile>>>

(Repeat per file)
Then a section:
<<<commands>>>
one shell command per line
<<<endcommands>>>

DO NOT include explanations. SPEC:

{spec}
"""
headers = {"x-api-key": os.environ["ANTHROPIC_API_KEY"], "content-type":"application/json"}
data = {
  "model":"claude-3-5-sonnet-latest",
  "max_tokens": 4096,
  "messages":[{"role":"user","content":prompt}]
}
res = requests.post("https://api.anthropic.com/v1/messages", headers=headers, data=json.dumps(data)).json()
text = "".join([b.get("text","") for b in res.get("content",[]) if b.get("type")=="text"])
open("claude_out.txt","w",encoding="utf-8").write(text)
PY

      - name: Parse + Write Files
        id: write
        run: |
          python - << 'PY'
import re, os, pathlib
txt = open("claude_out.txt", encoding="utf-8").read()
files = re.findall(r"<<<file:(.+?)>>>\n(.*?)\n<<<endfile>>>", txt, flags=re.S)
for path, code in files:
  p = pathlib.Path(path)
  p.parent.mkdir(parents=True, exist_ok=True)
  p.write_text(code, encoding="utf-8")
cmds = re.findall(r"<<<commands>>>\n(.*?)\n<<<endcommands>>>", txt, flags=re.S)
open("commands.txt","w",encoding="utf-8").write(cmds[0] if cmds else "")
PY

      - name: Create Branch, Commit, PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BR="auto/sc-${{ github.event.issue.number }}"
          git checkout -b "$BR"
          git add -A
          git -c user.name="ai-implementer" -c user.email="bot@users.noreply.github.com" commit -m "AI: implement SC-${{ github.event.issue.number }}"
          git push -u origin "$BR"
          gh pr create --title "AI: SC #${{ github.event.issue.number }}" --body "Auto-generated by Implementer" --head "$BR"
