name: Implementer (Claude)
permissions:
  contents: write
  pull-requests: write

on:
  issues:
    types:
      - opened
      - edited
      - labeled

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Implement with Claude
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
        run: node .github/scripts/implementer.js
