name: Implementer (Claude)
permissions:
  contents: write
  pull-requests: write

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  build-feature:
    # Alleen draaien als het issue het label 'spec' heeft
    if: contains(github.event.issue.labels.*.name, 'spec')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Call Anthropic & write files
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: node .github/scripts/implementer.js

      - name: Create branch, commit, push
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BR="auto/sc-${{ github.event.issue.number }}"
          git checkout -b "$BR"
          git add -A
          git -c user.name="ai-implementer" -c user.email="bot@users.noreply.github.com" commit -m "AI: implement SC-${{ github.event.issue.number }}"
          git push -u origin "$BR"

      - name: Open PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "AI: SC #${{ github.event.issue.number }}" \
            --body "Auto-generated by Implementer" \
            --head "auto/sc-${{ github.event.issue.number }}"
