name: Reviewer (ChatGPT-5)
permissions:
  pull-requests: write
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Diff
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff origin/${{ github.base_ref }}... --unified=0 > diff.patch
      - name: Ask ChatGPT-5 for Review
        id: gpt
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python - << 'PY'
import os, json, requests
diff = open("diff.patch","r",encoding="utf-8",errors="ignore").read()[:200000]
prompt = f"""
You are a Staff Engineer. Review this diff for correctness, security (Firebase Rules, signed URLs), performance (PDF/IFC budgets), accessibility, and test coverage.
Return ONLY markdown with:
1) SUMMARY
2) BLOCKERS (must fix)
3) SUGGESTIONS
4) TESTS to add
Diff:
{diff}
"""
res = requests.post("https://api.openai.com/v1/chat/completions",
  headers={"Authorization":f"Bearer {os.environ['OPENAI_API_KEY']}", "Content-Type":"application/json"},
  json={"model":"gpt-5-think-preview","messages":[{"role":"user","content":prompt}], "temperature":0}
).json()
text = res["choices"][0]["message"]["content"]
open("review.md","w",encoding="utf-8").write(text)
PY
      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.pull_request.number }} -F review.md
